#!/bin/bash
## anagram
## version 0.0.1 - initial
##################################################
anagram() { { local instr ; instr="${@}" ; }
  local i
  for i in $( seq ${#instr} | sort --random-sort )
  do
   echo -n ${instr:$(( ${#instr} - ${i} )):1}
  done
}
##################################################
if [ ! ] 
then
 true
else
 exit 1 # wrong args
fi
##################################################
anagram ${@}
##################################################
## generated by create-stub2.sh v0.1.2
## on Wed, 23 Oct 2019 13:54:35 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
